{"hierarchy":{"paths":[["doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dxfeedframework\/promise\/allof(promises:)"]}],"abstract":[{"text":"Returns a new promise that ","type":"text"},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isDone()","isActive":true,"type":"reference"},{"text":" completes when all promises from the given array","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"complete normally or exceptionally."},{"type":"text","text":" "},{"text":"The results of the given promises are not reflected in the returned promise, but may be","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"obtained by inspecting them individually. If no promises are provided, returns a promise completed"},{"type":"text","text":" "},{"text":"with the value null.","type":"text"},{"type":"text","text":" "},{"text":"When the resulting promise completes for any reason ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/cancel()"},{"type":"text","text":" canceled, for example)"},{"type":"text","text":" "},{"type":"text","text":"then all of the promises from the given array are canceled."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/allOf(promises:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allOf"},{"kind":"text","text":"("},{"text":"promises","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise","text":"Promise","kind":"typeIdentifier","preciseIdentifier":"s:15DXFeedFramework7PromiseC"},{"kind":"text","text":"]) "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise","text":"Promise","kind":"typeIdentifier","preciseIdentifier":"s:15DXFeedFramework7PromiseC"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Throws : GraalException. Rethrows exception from Java"}]}]}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"allOf","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"promises"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:15DXFeedFramework7PromiseC","text":"Promise","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Promise","preciseIdentifier":"s:15DXFeedFramework7PromiseC"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Type Method","title":"allOf(promises:)","symbolKind":"method","externalID":"s:15DXFeedFramework7PromiseC5allOf8promisesACSgSayACG_tKFZ","modules":[{"name":"DXFeedFramework"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/complete(result:)":{"role":"symbol","title":"complete(result:)","type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/complete(result:)","url":"\/documentation\/dxfeedframework\/promise\/complete(result:)","abstract":[{"type":"text","text":"Completes computation normally with a specified result."},{"type":"text","text":" "},{"type":"text","text":"This method does nothing if computation has already "},{"isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isDone()","type":"reference"},{"type":"text","text":" completed"},{"text":" ","type":"text"},{"type":"text","text":"(normally, exceptionally, or was cancelled),"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"complete","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"result"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MarketEvent","preciseIdentifier":"s:15DXFeedFramework11MarketEventC"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/isDone()":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isDone()","abstract":[{"type":"text","text":"Returns "},{"type":"strong","inlineContent":[{"type":"text","text":"true"}]},{"text":" when computation has","type":"text"},{"text":" ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/complete(result:)"},{"type":"text","text":" completed normally,"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/completeExceptionally(_:)","isActive":true},{"text":" exceptionally,","type":"text"},{"text":" ","type":"text"},{"text":"or was ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/cancel()"},{"type":"text","text":" canceled"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isDone","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isDone()","role":"symbol","url":"\/documentation\/dxfeedframework\/promise\/isdone()"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise":{"abstract":[{"text":"Result of a computation that will be completed normally or exceptionally in the future.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This class is designed to represent a promise to deliver certain result."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Promise","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Promise"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise","title":"Promise","type":"topic","kind":"symbol","url":"\/documentation\/dxfeedframework\/promise"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/allOf(promises:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/allOf(promises:)","abstract":[{"text":"Returns a new promise that ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isDone()"},{"type":"text","text":" completes when all promises from the given array"},{"type":"text","text":" "},{"type":"text","text":"complete normally or exceptionally."},{"text":" ","type":"text"},{"type":"text","text":"The results of the given promises are not reflected in the returned promise, but may be"},{"text":" ","type":"text"},{"text":"obtained by inspecting them individually. If no promises are provided, returns a promise completed","type":"text"},{"type":"text","text":" "},{"type":"text","text":"with the value null."},{"text":" ","type":"text"},{"type":"text","text":"When the resulting promise completes for any reason "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/cancel()","type":"reference","isActive":true},{"type":"text","text":" canceled, for example)"},{"text":" ","type":"text"},{"type":"text","text":"then all of the promises from the given array are canceled."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allOf"},{"text":"(","kind":"text"},{"text":"promises","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Promise","kind":"typeIdentifier","preciseIdentifier":"s:15DXFeedFramework7PromiseC"},{"kind":"text","text":"]) "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Promise","preciseIdentifier":"s:15DXFeedFramework7PromiseC"},{"text":"?","kind":"text"}],"title":"allOf(promises:)","role":"symbol","url":"\/documentation\/dxfeedframework\/promise\/allof(promises:)"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/cancel()":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/cancel()","abstract":[{"type":"text","text":"Cancels computation. This method does nothing if computation has already "},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isDone()","isActive":true},{"text":" completed.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"kind":"text","text":"()"}],"title":"cancel()","role":"symbol","url":"\/documentation\/dxfeedframework\/promise\/cancel()"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework":{"type":"topic","title":"DXFeedFramework","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework","url":"\/documentation\/dxfeedframework"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise/completeExceptionally(_:)":{"role":"symbol","title":"completeExceptionally(_:)","type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/completeExceptionally(_:)","url":"\/documentation\/dxfeedframework\/promise\/completeexceptionally(_:)","abstract":[{"text":"Completes computation exceptionally with a specified exception.","type":"text"},{"type":"text","text":" "},{"text":"This method does nothing if computation has already ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/isDone()","type":"reference"},{"type":"text","text":" completed,"},{"type":"text","text":" "},{"type":"text","text":"otherwise "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise\/getException()","isActive":true,"type":"reference"},{"text":" will return the specified exception.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completeExceptionally","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:15DXFeedFramework14GraalExceptionO","text":"GraalException"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]}}}